# .github/release.yml

changelog:
  categories:
    - title: What's new
      labels:
        - "*"
      exclude:
        labels:
          - "dependencies"
    - title: Renovate
      labels:
        - "dependencies"
