version: '3'

volumes:
  production_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ds_judgements_public_ui_production_django
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
    environment:
      MARKLOGIC_HOST: marklogic
    command: /start

  marklogic:
    container_name: marklogic
    image: store/marklogicdb/marklogic-server:10.0-8.1-centos-1.0.0-ea2
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8011:8011"
    environment:
      MARKLOGIC_ADMIN_USERNAME: admin
      MARKLOGIC_ADMIN_PASSWORD: admin
      MARKLOGIC_INIT: "true"
    volumes:
      - ./docker/db/data/:/var/opt/MarkLogic/
      - ./docker/db/backup:/var/opt/backup

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: ds_judgements_public_ui_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
