# Generated by Django 3.2.23 on 2023-11-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgments', '0001_create_court_dates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtdates',
            options={'verbose_name': 'court date range', 'verbose_name_plural': 'court date ranges'},
        ),
    ]
