#!/bin/sh
# vim: set ts=4:
#
# Ensures that Python 3.9 is available and installs modules specified
# in requirements-dev.txt.
#
# Environment variables:
#   PYTHON : Python executable to use (default is python3 or python on PATH).
#
# This script follows convention https://github.com/github/scripts-to-rule-them-all.
set -eu

cd "$(dirname "$0")/.."
. script/utils.sh
. .env

readonly ENV_DIR="$(pwd)/.venv"

if [ ! -f "$ENV_DIR/bin/python3" ]; then
	info 'Initializing Python virtual environment...'

	# Find Python executable.
	for pybin in "${PYTHON:-}" python3 python NOT_FOUND; do
		command -v "$pybin" 2>&1 >/dev/null && break
	done
	if [ "$pybin" = 'NOT_FOUND' ]; then
		die 'Could not find python executable! Please install Python 3.9.'
	fi

	if ! "$pybin" -c 'import sys; exit(not sys.version_info >= (3, 9, 0))'; then
		die "Python 3.9+ is required, but you have $("$pybin" -V 2>&1)!"
	fi

	"$pybin" -m venv "$ENV_DIR"

	# For the case when PATH is already set, but venv was empty.
	hash -r 2>&1 >/dev/null
fi

info 'Installing Python modules...'
python3 -m pip install --disable-pip-version-check -r requirements/local.txt 2>&1 \
	| sed	-e '/^Requirement already satisfied/d' \
			-e '/don.t match your environment$/d'

info 'Read .env file...'
export DJANGO_READ_DOT_ENV_FILE=True
info 'Setting up DATABASE_URL...'
export DATABASE_URL=$DATABASE_URL
info 'Create database...'
createdb ds_judgements_public_ui -U postgres --no-password $DATABASE_PASSWORD 2>&1 \
  | sed -e '/database "ds_judgements_public_ui" already exists$/d'
info 'Migrate database...'
python3 manage.py migrate

info 'Create data volume for Marklogic'
mkdir -p docker/db/data 2>&1 \
  | sed -e '/File exists$/d'

info 'Bring up Marklogic...'
docker-compose -f docker-marklogic.yml up -d > marklogic.log

info 'Check to see if Marklogic is up...'
while ! curl -X GET http://localhost:8002/v1/rest-apis 2>&1 | sed -e '/401 Unauthorized/d'
do
  sleep 1
  echo 'Waiting for Marklogic to come up'
done

info 'Create Application server on Marklogic...'
  curl -v -X POST  --anyauth -u admin:admin \
  --header "Content-Type:application/json" \
  -d '{"rest-api": { "name": "JudgmentsServer", "port": "8011", "database": "Judgments", "modules-database": "Modules" } }' \
  'http://localhost:8002/v1/rest-apis' 2>&1 \
  | sed -e '/Port 8011 is in use./d' # This message means the application server already exists

info 'Adjust Application server authentication to be basicauth...'
  curl -v -X PUT  --anyauth -u admin:admin \
  --header "Content-Type:application/json" \
  -d '{"authentication": "basic" }' \
  'http://localhost:8002/manage/v2/servers/JudgmentsServer/properties?group-id=Default' 2>&1 \
  | sed -e '/204 No Content/d'

info "Don't forget to import data into Marklogic! See README for details"
