#!/bin/sh
# vim: set ts=4:
#
# Ensures that Python 3.9 is available and installs modules specified
# in requirements-dev.txt.
#
# Environment variables:
#   PYTHON : Python executable to use (default is python3 or python on PATH).
#
# This script follows convention https://github.com/github/scripts-to-rule-them-all.
set -eu

cd "$(dirname "$0")/.."
. script/utils.sh
. .env

info 'Create data volume for Marklogic'
mkdir -p docker/db/data 2>&1 \
  | sed -e '/File exists$/d'

info 'Bring up Marklogic...'
docker-compose up -d marklogic > marklogic.log

info 'Check to see if Marklogic is up...'
while ! curl -X GET http://localhost:8002/v1/rest-apis 2>&1 | sed -e '/401 Unauthorized/d'
do
  sleep 1
  echo 'Waiting for Marklogic to come up'
done

info 'Create Application server on Marklogic...'
  curl -v -X POST  --anyauth -u admin:admin \
  --header "Content-Type:application/json" \
  -d '{"rest-api": { "name": "JudgmentsServer", "port": "8011", "database": "Judgments", "modules-database": "Modules" } }' \
  'http://localhost:8002/v1/rest-apis' 2>&1 \
  | sed -e '/Port 8011 is in use./d' # This message means the application server already exists

info 'Adjust Application server authentication to be basicauth...'
  curl -v -X PUT  --anyauth -u admin:admin \
  --header "Content-Type:application/json" \
  -d '{"authentication": "basic" }' \
  'http://localhost:8002/manage/v2/servers/JudgmentsServer/properties?group-id=Default' 2>&1 \
  | sed -e '/204 No Content/d'

info 'Marklogic Application server created'
