#!/bin/sh
# vim: set ts=4:
#
# Runs server
#
# This script follows convention https://github.com/github/scripts-to-rule-them-all.
set -u

. "$(dirname "$0")/bootstrap"

info 'Bring up Marklogic in the background...'
docker-compose -f docker-marklogic.yml up -d
info 'Piping Marklogic logs to marklogic.log...'
docker logs marklogic > marklogic.log

info 'Running server...'
python3 manage.py runserver 3000
