#!/bin/sh
# vim: set ts=4:
#
# Runs linters, tests etc.
#
# This script follows convention https://github.com/github/scripts-to-rule-them-all.
set -u

. "$(dirname "$0")/bootstrap"

info 'Checking types...'
mypy ds_judgements_public_ui

info 'Running tests...'
pytest
