#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


npm run build
python /app/manage.py collectstatic --noinput
cd /app
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --access-logfile - -w 5
