name: Publish Storybook to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "storybook/**"
      - "ds_judgements_public_ui/templates/**"
      - "ds_judgements_public_ui/static/**"
      - "ds_judgements_public_ui/sass/**"
      - "package.json"
      - "package-lock.json"
      - "webpack.config.js"
      - "babel.config.js"
      - ".github/workflows/publish-storybook.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          cache: npm

      - name: Install node dependencies
        run: npm ci

      - name: Build Storybook
        env:
          STORYBOOK_SERVER: https://caselaw.nationalarchives.gov.uk
        run: npm run build-storybook

      - name: Configure Pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d # v4

      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
