name: Publish Storybook to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "storybook/**"
      - "ds_judgements_public_ui/templates/**"
      - "ds_judgements_public_ui/static/**"
      - "ds_judgements_public_ui/sass/**"
      - "package.json"
      - "package-lock.json"
      - "webpack.config.js"
      - "babel.config.js"
      - ".github/workflows/publish-storybook.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Set up node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          cache: npm

      - name: Install node dependencies
        run: npm ci

      - name: Build Storybook
        env:
          STORYBOOK_SERVER: https://caselaw.nationalarchives.gov.uk
        run: npm run build-storybook

      - name: Configure Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6

      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          path: storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
