name: Source safety
permissions: {}
on:
  pull_request:
  push:
jobs:
  secrets:
    name: Check for secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@af4df0b5325dcd5277e8291745c9e5a7d2e68d79
